version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./ecommerce_backend
    command: sh -c "python wait_for_db.py &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ecommerce_backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  frontend:
    build: ./ecommerce_frontend
    command: npm start
    volumes:
      - ./ecommerce_frontend:/code
    ports:
      - "3000:3000"
  crawler:
    build: ./ecommerce_crawler
    # for the first time run crawler 
    # command: sh -c "python wait_for_db.py &&
            #  scrapy crawl ontopspider"
    # for other times run crawler
    command: sh -c "python hello.py"
    volumes:
      - ./ecommerce_crawler:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db