# Generated by Django 4.0.3 on 2022-03-22 09:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('type_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type_tag', models.CharField(max_length=8000)),
                ('type_detail', models.CharField(max_length=8000)),
                ('refer_image', models.TextField(null=True)),
                ('type_url', models.TextField(default='temp-category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(editable=False, max_length=8000, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=8000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_s_total', models.IntegerField(default=100)),
                ('size_s_remain', models.IntegerField(default=100)),
                ('size_m_total', models.IntegerField(default=100)),
                ('size_m_remain', models.IntegerField(default=100)),
                ('size_l_total', models.IntegerField(default=100)),
                ('size_l_remain', models.IntegerField(default=100)),
                ('type_id', models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_api.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='project_api.product')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productratings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_s_total', models.IntegerField(default=0)),
                ('size_m_total', models.IntegerField(default=0)),
                ('size_l_total', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='project_api.product')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
